---
image: Visual Studio 2017

cache:
  - vendor/bundle

branches:
  only:
    - master

environment:
  matrix:
    - RUBY_VERSION: "25-x64"

# scripts that are called at very beginning, before repo cloning
init:
  - ps: Set-ItemProperty -Path HKLM:\SYSTEM\CurrentControlSet\Control\FileSystem -Name LongPathsEnabled -Value 1 -Type DWord

matrix:
  fast_finish: false

install:
  - set PATH=C:\Ruby%RUBY_VERSION%\bin;%PATH%
  - bundle config --local path vendor/bundle
  - bundle install

build: "off"

before_test:
  - ruby -v
  - gem -v
  - bundle -v

test_script:
  - ps: New-Item -ItemType Directory -Force -Path C:/ProgramData/PuppetLabs/puppet/etc
  - ps: New-Item -ItemType File C:/ProgramData/PuppetLabs/puppet/etc/puppet.conf
  - ps: Write-Host $env:APPVEYOR_BUILD_FOLDER
  - ps: Write-Host (get-item $env:APPVEYOR_BUILD_FOLDER).parent
  - ps: bundle exec puppet config set basemodulepath (get-item $env:APPVEYOR_BUILD_FOLDER).parent
  - ps: $env:TARGET_HOST="localhost"; bundle exec rspec spec/acceptance
